Use different matplotlib backend
I could not run detect.py via an ssh connection on a remote server, got
the error:

File "/usr/lib/python3.8/tkinter/__init__.py", line 2261, in __init__
    self.tk = _tkinter.create(screenName, baseName, className,
interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "localhost:11.0"

Fixed this by using a pdf backend instead of an interactive backend.